name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Angular
        run: npm install -g @angular/cli

      - run: npm install
      - name: Production Build
        run: ng build --prod --base-href https://bymartrixx.github.io
      - name: Deploy to Github Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/
